name: demo02
on: push
env:
  env_var: ${{ vars.APPLICATION_NAME }}
jobs:
  checklist:
    runs-on: self-hosted
    steps:
      - name: List Variables 
        run: set
      - name: Application name
        run: echo $env_var
